services:

  backend:
    build: .
    container_name: asteristico-backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"
  spring:
    datasource:
      hikari:
        maximum-pool-size: 5
        minimum-idle: 1
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000