spring.application.name=asteristico

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xozmcslyaezfomimzlhc
spring.datasource.password=Q2e4t6u8o0@

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
api.security.token.secret=wI4yAWouVQtZW5LH7Dd9awJHFdEH8bqoaeuu6c2OTlLAaZDmoYMVqyvUXAaHvz0S
cloudinary.cloud-name=t8awtqrh
cloudinary.api-key=186779729777769
cloudinary.api-secret=NmSUgF68EUpRmBLfQWsGmNScE2s